# Generated by Django 4.2.1 on 2023-08-20 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Uživatelské jméno')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Vytvoření')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Poslední přihlášení')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_sekretar', models.BooleanField(default=False)),
                ('is_seftrener', models.BooleanField(default=False)),
                ('is_veteran', models.BooleanField(default=False)),
                ('is_repre', models.BooleanField(default=False)),
                ('is_zdr', models.BooleanField(default=False)),
                ('is_predseda', models.BooleanField(default=False)),
                ('is_organizator', models.BooleanField(default=False)),
                ('is_clen', models.BooleanField(default=False)),
                ('is_registrovany', models.BooleanField(default=True)),
                ('is_neregistrovany', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='Jméno')),
                ('second_name', models.CharField(max_length=30, verbose_name='Příjmení')),
                ('index', models.CharField(max_length=7, unique=True, verbose_name='Index')),
                ('si_number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(8999999), django.core.validators.MinValueValidator(1000)], verbose_name='Číslo čipu')),
                ('club', models.CharField(blank=True, max_length=3)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
