# Generated by Django 4.2.1 on 2023-08-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='index',
            field=models.CharField(default=django.utils.timezone.now, max_length=7, unique=True, verbose_name='Index'),
            preserve_default=False,
        ),
    ]
