# Generated by Django 4.2.1 on 2023-08-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kalendar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('zprava_info', models.CharField(blank=True, max_length=500)),
                ('zprava_warning', models.CharField(blank=True, max_length=500)),
                ('mapa', models.ImageField(blank=True, upload_to=kalendar.models.upload_location)),
                ('bulletin', models.FileField(blank=True, upload_to=kalendar.models.upload_location)),
                ('pokyny', models.FileField(blank=True, upload_to=kalendar.models.upload_location)),
                ('startlist', models.FileField(blank=True, upload_to=kalendar.models.upload_location)),
                ('results', models.FileField(blank=True, upload_to=kalendar.models.upload_location)),
                ('splittimes', models.FileField(blank=True, upload_to=kalendar.models.upload_location)),
                ('event_date', models.DateField()),
                ('event_date_end', models.DateField(blank=True, null=True)),
                ('termin_prihl', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('ostatni', 'Ostatní'), ('mcr-nz', 'MČR/NŽ - I. stupeň'), ('repre', 'Reprezentační'), ('zdr', 'ŽDR')], max_length=20)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Datum publikace')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('club', models.CharField(blank=True, max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microevent_id', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='MicroEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.microevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('index', models.CharField(max_length=7)),
                ('si_number', models.IntegerField()),
                ('category', models.CharField(choices=[('mdr', 'MDR'), ('m12', 'M12'), ('m14', 'M14'), ('m16', 'M16'), ('m19', 'M19'), ('m20', 'M20'), ('m40', 'M40'), ('m50', 'M50'), ('m60', 'M60'), ('m70', 'M70'), ('d12', 'D12'), ('d14', 'D14'), ('d16', 'D16'), ('d19', 'D19'), ('d20', 'D20'), ('d35', 'D35'), ('d45', 'D45'), ('d55', 'D55'), ('d65', 'D65')], default='m20', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost')),
            ],
        ),
    ]
