# Generated by Django 4.2.1 on 2023-08-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='microevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='microevent',
            name='microevent_id',
        ),
        migrations.AddField(
            model_name='microevent',
            name='event_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microevent',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MicroEventEntry',
        ),
        migrations.AddField(
            model_name='microentry',
            name='microevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.microevent'),
        ),
        migrations.AddField(
            model_name='microentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
