# Generated by Django 4.2.1 on 2023-08-20 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0002_microentry_remove_microevent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microentry',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
