# Generated by Django 4.2.1 on 2023-08-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0003_microentry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevent',
            name='title',
        ),
        migrations.AddField(
            model_name='microevent',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
