# Generated by Django 4.2.1 on 2023-08-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0004_remove_microevent_title_microevent_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevent',
            name='event_detail',
        ),
        migrations.DeleteModel(
            name='Microentry',
        ),
        migrations.DeleteModel(
            name='MicroEvent',
        ),
    ]
