# Generated by Django 4.2.1 on 2023-08-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalendar', '0005_remove_microevent_event_detail_delete_microentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='MicroEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('microevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.microevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='microevent',
            name='participants',
            field=models.ManyToManyField(through='kalendar.MicroEventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
