# Generated by Django 4.2.1 on 2023-08-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0006_microevent_microeventparticipant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevent',
            name='event_date',
        ),
    ]
