# Generated by Django 4.2.1 on 2023-08-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0007_remove_microevent_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevent',
            name='description',
        ),
    ]
