# Generated by Django 4.2.1 on 2023-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0008_remove_microevent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automodul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AutomodulEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='microeventparticipant',
            name='microevent',
        ),
        migrations.RemoveField(
            model_name='microeventparticipant',
            name='user',
        ),
        migrations.DeleteModel(
            name='MicroEvent',
        ),
        migrations.DeleteModel(
            name='MicroEventParticipant',
        ),
    ]
