# Generated by Django 4.2.1 on 2023-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0009_automodul_automodulentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Automodul',
        ),
        migrations.DeleteModel(
            name='AutomodulEntry',
        ),
    ]
