# Generated by Django 4.2.1 on 2023-08-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0010_textmodel_delete_automodul_delete_automodulentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
