# Generated by Django 4.2.1 on 2023-08-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0011_alter_textmodel_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextModel',
        ),
    ]
