# Generated by Django 4.2.1 on 2023-08-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0012_delete_textmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Database Data',
            },
        ),
    ]
