# Generated by Django 4.2.1 on 2023-08-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0013_databasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.dynamicform')),
            ],
        ),
        migrations.DeleteModel(
            name='DatabaseData',
        ),
    ]
