# Generated by Django 4.2.1 on 2023-08-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0014_dynamicform_dynamicformfield_delete_databasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_entries', models.PositiveIntegerField()),
                ('entry_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dynamicformfield',
            name='dynamic_form',
        ),
        migrations.DeleteModel(
            name='DynamicForm',
        ),
        migrations.DeleteModel(
            name='DynamicFormField',
        ),
    ]
