# Generated by Django 4.2.1 on 2023-08-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0015_event_remove_dynamicformfield_dynamic_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntry2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notice', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
