# Generated by Django 4.2.1 on 2023-08-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0016_evententry2_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('main_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='MicroEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('microevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.microevent')),
            ],
        ),
        migrations.DeleteModel(
            name='EventEntry2',
        ),
    ]
