# Generated by Django 4.2.1 on 2023-08-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0018_remove_microevent_note_remove_microevent_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notice', models.CharField(max_length=100)),
                ('micro_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalendar.microevent')),
            ],
        ),
    ]
