# Generated by Django 4.2.1 on 2023-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0020_microevententry_microevent_microevententry_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microevententry',
            name='notice',
        ),
        migrations.AddField(
            model_name='microevententry',
            name='notice_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='microevent',
            name='notice',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
