# Generated by Django 4.2.1 on 2023-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0022_alter_microevent_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='contact',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='discipline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='gps',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='start00',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evententry',
            name='note',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='event_type',
            field=models.CharField(choices=[('ostatni', 'Ostatní'), ('tc-oddil', 'Oddílové soustředění'), ('3', 'soutěž III. stupně'), ('2', 'soutěž II. stupně'), ('mcr-nz', 'MČR/NŽ - I. stupeň'), ('repre', 'Reprezentační akce'), ('zdr', 'ŽDR akce')], max_length=20),
        ),
    ]
