# Generated by Django 4.2.1 on 2023-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0023_blogpost_contact_blogpost_discipline_blogpost_gps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='discipline',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='event_type',
            field=models.CharField(choices=[('ostatni', 'Ostatní'), ('tc-oddil', 'Oddílové soustředění'), ('3', 'soutěž III. stupně'), ('2', 'soutěž II. stupně'), ('mcr-nz', 'MČR/NŽ - I. stupeň'), ('repre', 'Reprezentační akce'), ('zdr', 'ŽDR akce')], max_length=30),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='gps',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='category',
            field=models.CharField(choices=[('mdr', 'MDR'), ('m12', 'M12'), ('m14', 'M14'), ('m16', 'M16'), ('m19', 'M19'), ('m20', 'M20'), ('m40', 'M40'), ('m50', 'M50'), ('m60', 'M60'), ('m70', 'M70'), ('d12', 'D12'), ('d14', 'D14'), ('d16', 'D16'), ('d19', 'D19'), ('d20', 'D20'), ('d35', 'D35'), ('d45', 'D45'), ('d55', 'D55'), ('d65', 'D65')], default='m20', max_length=5),
        ),
        migrations.AlterField(
            model_name='evententry',
            name='note',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='microevent',
            name='notice',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='microevententry',
            name='notice_name',
            field=models.CharField(max_length=80),
        ),
    ]
