# Generated by Django 4.2.1 on 2023-08-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0027_alter_microevententry_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='microevententry',
            unique_together=set(),
        ),
    ]
